<a href="https://colab.research.google.com/github/krishks10/SimpleProject/blob/main/IntroToNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
tempreatures = [32.5, 31.8, 33.0, 35.2, 36.6]

total = 0
for temp in tempreatures:
    total += temp
average = total / len(tempreatures)
print(average)

33.82


In [ ]:
import numpy as np

tempreatures = np.array([32.5, 31.8, 33.0, 35.2, 36.6])
average = np.mean(tempreatures)
print(average)

33.82


In [ ]:
python_list = [1, 2, 3, 4, 5]
print(python_list)

import numpy as np
numpy_array = np.array([1, 2, 3, 4, 5])
print(numpy_array)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
mark1 = 85
mark2 = 90
mark3 = 95
mark4 = 45
marks = [85, 90, 95, 89]
print(marks)

[85, 90, 95, 89]


In [ ]:
import numpy as np
ar_1d = np.array([10, 20, 30, 40, 50])

print(ar_1d)

[10 20 30 40 50]


In [ ]:
import numpy as np

zeros_array = np.zeros(6)
print(zeros_array)

[0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np

ones_array = np.ones((3,6))
print(ones_array)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [1]:
import numpy as np

empty_array = np.empty((2,3))
print(empty_array)

[[5.13121675e-315 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [3]:
import numpy as np

identity_matrix = np.eye(9)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [4]:
import numpy as np

random_array = np.random.rand(3, 4)
print(random_array)

[[0.96571371 0.8697607  0.05852553 0.3048358 ]
 [0.09930967 0.20071093 0.62409482 0.61857917]
 [0.27824715 0.63516283 0.39552715 0.28022174]]


In [8]:
import numpy as np

arr_2d = np.array([[10, 20, 30],
                   [3, 6, 9]])
print(arr_2d.shape)

(2, 3)


In [9]:
import numpy as np

arr_2d = np.array([[10, 20, 30],
                   [3, 6, 9]])
print(arr_2d.size)

6
